
version: 2.1
commands:
  print_pipeline_id:
    description: "A pipeline that prints the workflow ID"
    parameters:
      to:
        type: string
        default: "My_id"
    steps:
      - run: echo << parameters.to >>
executors:
  my-executor:
    docker:
      - image: cimg/base:stable
         # context / project UI env-var reference
    working_directory: /tmp

jobs:

  say-hello:
    
    docker:
      - image: cimg/base:stable
    
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say Hello world again"
          command: "echo Hello"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say Hello world again"
          command: "echo World"

  print_authors_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print out author's name"
          command: echo $password

  save_job_description:
    executor: my-executor
    
    steps:
      - run : mkdir -p workspace
      - run:
          name: "Print job role to a file"
          command: echo "Systems Analyst" > workspace/output.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - output.txt

  print_job_description:
    executor: my-executor
    
    steps:
      
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Print job role command output"
          command: cat /tmp/workspace/output.txt
  failed_test:
    executor: my-executor
    
    steps:
      
      - attach_workspace:
          at: /failed_jobs
      - run:
          name: "Print job role command output"
          command: cat /failed_jobs/output.txt
      - run:
          name: Upload failed tests
          command: echo "A job failed" 
          when: on_fail
          
    
          
  print_workflow_id:
    executor: my-executor
    
    steps:
      - print_pipeline_id:
          to: ${CIRCLE_WORKFLOW_ID}
          

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_authors_name
      - save_job_description
      - print_job_description:
          requires: [save_job_description]
      - print_workflow_id
      - failed_test
