# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "A pipeline that prints the workflow ID"
    parameters:
      to:
        type: integer
        default: 1
    steps:
      - run echo << parameters.to >>
executors:
  my-executor:
    docker:
      - image: cimg/base:stable
         # context / project UI env-var reference
    working_directory: /tmp
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say Hello world again"
          command: "echo Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say Hello world again"
          command: "echo World"
  print_authors_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print out author's name"
          command: echo $password
  save_job_description:
    executor: my-executor
    
    steps:
      - run : mkdir -p workspace
      - run:
          name: "Print job role to a file"
          command: echo "Systems Analyst" > workspace/output.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - output.txt
  print_job_description:
    executor: my-executor
    
    steps:
      
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Print job role command output"
          command: cat /tmp/workspace/output.txt
  print_workfow-id:
    executor: my-executor
    
    steps:
      - print_pipeline_id:
          to: $CIRCLE_WORKFLOW_ID
          
#made some changesss
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_authors_name
      - save_job_description
      - print_job_description:
          requires: [save_job_description]
      - print_workfow-id
